### ISSUE TITLE
I keep getting issues to do with firewall

### ISSUE THREAD

**Issue by ghost** [antonioCoco/ConPtyShell#9]
I am on windows 11 and doing this to myself with kali linux VM and was wondering what I do to make it work because I cannot turn off my real time protection on my computer (I dont know why). and I keep getting the error: ConPtyShellException: [-] ConPtyShellException: WSAConnect failed with error code: 10060
   at ConPtyShell.connectRemote(String remoteIp, Int32 remotePort)
   at ConPtyShell.SpawnConPtyShell(String remoteIp, Int32 remotePort, UInt32 rows, UInt32 cols, String commandLine, Boolean upgradeShell)
   at ConPtyShellMainClass.ConPtyShellMain(String[] args)

Thank you!

**Comment by antonioCoco** [comment]
This is a generic error with Winsock. Highly likely there is something between the two ends (client or server) that is blocking the communication, or simply you are specifying wrong parameters.

Please include commandline and scenario next time for troubleshooting better the issue.

**Comment by TheMasterProgrammer** [comment]
Same issue here
